url         = "http://atelierfusilli.ch/"
theme           = "casper1"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 10

#SectionPagesMenu = "main"
canonifyurls    = true  

[params]
  title       = "FUSILLI"
  subtitle    = "FUSILLI – Ateliergemeinschaft Teiggi Kriens "
copyright     = "© 2019"

  cover       = ""
  description = "FUSILLI– Ateliergemeinschaft Teiggi Kriens "
  metaDescription = ""
  googleAnalytics = ""

  customCSS = ["/css/fusilli.css"]  
  RSSLink = ""

  twitterName = ""
  fbName = "586121398408539"
  instagramName = "fusilli.teiggi"
instagramLink = "www.instagram.com/fusilli.teiggi"
  logo = "/fusilli-logo.png"
  orgName = ""
  orgWebsite = ""
  orgDescription = ""

  showSupport = true

  author = ""
  authorAvatar = ""
  authorLocation = ""
  authorWebsite = ""
  authorDescription = ""

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/post/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Über uns"
  url = "/about/"
  weight = 95
  
[[menu.main]]
  name = "Partner"
  url = "/partner/"
  weight = 60
 

